### ISSUE TITLE
host.interface.default does not work consistently

### ISSUE THREAD

**Issue by sealeg** [pytest-dev/pytest-testinfra#652]
Looks like it expects the interface name to be at the end of `ip route ls` line.

So it works for something like: `default via 172.17.0.1 dev eth0` but not `default via 10.101.1.1 dev ens3 proto dhcp src 10.101.1.33 metric 100`.

**Comment by sealeg** [comment]
I have fixed with a regex in #651

**Comment by CarstenGrohmann** [comment]
@philpep: Please close this ticket as the issue has already been resolved with MR #651.
