### ISSUE TITLE
use testinfra python script as THE script

### ISSUE THREAD

**Issue by rismoney** [pytest-dev/pytest-testinfra#663]
So I am looking to get rid of an install process in a bash script outside of config mgmt handling.

Could I just create a single python script using testinfra, take advantage of its execution (ie invoke), output, analysis, assertion capabilities and not use it as a separate script.   Essentially in the Arrange, Act, Assert pattern, Can I just do the real thing in Arrange and Assert? 

Example  I dont want to just test a service is running in my testinfra script. I want to start it.  Then I can handle complex idempotency concerns beyond config mgmt.  Then write complex assertions.

Is this frowned upon? Isn't this a way better than starting a service in bash and checking its running, service listening, accepting conns, etc?  I dont want to unit test my script outside itself  because the functions all change real inf, and mocking is futile. Plus it would be nice to just get the execution of testinfra as the deployer.

Might this be the new way?

**Comment by philpep** [comment]
Feel free
