### ISSUE TITLE
Question: Why are we unquoting these variables?

### ISSUE THREAD

**Issue by tdas3001** [pytest-dev/pytest-testinfra#702]
https://github.com/pytest-dev/pytest-testinfra/blob/8520850b61e022b791c47fa6879aaf14e1cf6a1b/testinfra/backend/base.py#L233-L237

Why are we unquoting `name`, `user` and `password`? Are they being quoted somewhere in the code which we are trying to undo?

**Comment by philpep** [comment]
Because they can be passed in urlstring `pytest --host 'ssh://some%40user@host'`
