### ISSUE TITLE
Request for guidance on adding windows functionality to testinfra

### ISSUE THREAD

**Issue by ILoveCyber** [pytest-dev/pytest-testinfra#704]
Hello,

I am a user of testinfra and I would like to add some functionality to support more windows commands. I am not sure how to do it and I would appreciate some guidance from the maintainers. Is there a way to contribute to the project and have my code reviewed?

Some of the functionality that I think would be useful are:

- A module to check the status of windows services and processes, such as service.is_running(), service.is_enabled(), process.exists(), process.pid(), etc.
- A module to interact with the windows registry, such as registry.get_value(), registry.set_value(), registry.delete_key(), etc.
- A module to verify the configuration of windows firewall, such as firewall.is_enabled(), firewall.get_rules(), firewall.add_rule(), firewall.remove_rule(), etc.
- A module to manage windows users and groups, such as user.exists(), user.is_admin(), user.get_groups(), group.exists(), group.add_user(), group.remove_user(), etc.
- A module to perform file and directory operations on windows, such as file.exists(), file.is_file(), file.is_directory(), file.mode(), file.owner(), file.content(), directory.exists(), directory.is_directory(), directory.files(), directory.subdirectories(), etc.

Thank you for your time and attention.

**Comment by philpep** [comment]
TBH I've zero skills in windows. I'd rather suggest maintaining this as a dedicated projet.
